name: Viewber Email Alert

on:
  schedule:
    - cron: '* * * * *'  # Runs every 1 minute
  workflow_dispatch:      # Optional: allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run your script
      run: python viewber_email_alert.py
